/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurnoutRouteImport } from './routes/turnout'
import { Route as SwingRouteImport } from './routes/swing'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const TurnoutRoute = TurnoutRouteImport.update({
  id: '/turnout',
  path: '/turnout',
  getParentRoute: () => rootRouteImport,
} as any)
const SwingRoute = SwingRouteImport.update({
  id: '/swing',
  path: '/swing',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/insights': typeof InsightsRoute
  '/mapping': typeof MappingRoute
  '/methodology': typeof MethodologyRoute
  '/swing': typeof SwingRoute
  '/turnout': typeof TurnoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/insights': typeof InsightsRoute
  '/mapping': typeof MappingRoute
  '/methodology': typeof MethodologyRoute
  '/swing': typeof SwingRoute
  '/turnout': typeof TurnoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/insights': typeof InsightsRoute
  '/mapping': typeof MappingRoute
  '/methodology': typeof MethodologyRoute
  '/swing': typeof SwingRoute
  '/turnout': typeof TurnoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/insights'
    | '/mapping'
    | '/methodology'
    | '/swing'
    | '/turnout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/insights'
    | '/mapping'
    | '/methodology'
    | '/swing'
    | '/turnout'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/insights'
    | '/mapping'
    | '/methodology'
    | '/swing'
    | '/turnout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  InsightsRoute: typeof InsightsRoute
  MappingRoute: typeof MappingRoute
  MethodologyRoute: typeof MethodologyRoute
  SwingRoute: typeof SwingRoute
  TurnoutRoute: typeof TurnoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turnout': {
      id: '/turnout'
      path: '/turnout'
      fullPath: '/turnout'
      preLoaderRoute: typeof TurnoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swing': {
      id: '/swing'
      path: '/swing'
      fullPath: '/swing'
      preLoaderRoute: typeof SwingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  InsightsRoute: InsightsRoute,
  MappingRoute: MappingRoute,
  MethodologyRoute: MethodologyRoute,
  SwingRoute: SwingRoute,
  TurnoutRoute: TurnoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
